import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Image from "next/image";
import { useEffect, useState } from "react";
import Link from "next/link";

export default function Home() {
  const [menuActive, setMenuActive] = useState(false);

  useEffect(() => {
    const canvas = document.getElementById("Matrix");
    const context = canvas.getContext("2d");

    canvas.width = window.innerWidth;
    canvas.height = window.innerHeight;

    const katakana =
      "アァカサタナハマヤャラワガザダバパイィキシチニヒミリヰギジヂビピウゥクスツヌフムユュルグズブヅプエェケセテネヘメレヱゲゼデベペオォコソトノホモヨョロヲゴゾドボポヴッン";
    const latin = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
    const nums = "0123456789";

    const alphabet = katakana + latin + nums;

    const fontSize = 16;
    const columns = canvas.width / fontSize;

    const rainDrops = [];

    for (let x = 0; x < columns; x++) {
      rainDrops[x] = 1;
    }

    const draw = () => {
      context.fillStyle = "rgba(0, 0, 0, 0.05)";
      context.fillRect(0, 0, canvas.width, canvas.height);

      context.fillStyle = "#0F0";
      context.font = fontSize + "px monospace";

      for (let i = 0; i < rainDrops.length; i++) {
        const text = alphabet.charAt(
          Math.floor(Math.random() * alphabet.length)
        );
        context.fillText(text, i * fontSize, rainDrops[i] * fontSize);

        if (rainDrops[i] * fontSize > canvas.height && Math.random() > 0.975) {
          rainDrops[i] = 0;
        }
        rainDrops[i]++;
      }
    };

    setInterval(draw, 30);
  }, []);

  return (
    <>
      <Head>
        <title>Phenomena</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.jpg" />
      </Head>
      <main>
        <div className={styles.bigContainer}>
          <canvas id="Matrix"></canvas>
          <nav className={`${styles.nav} ${menuActive && styles.navActive}`}>
            {menuActive ? (
              <div
                className={styles.close}
                onClick={() => setMenuActive(false)}
              >
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="40px"
                  height="40px"
                  fill="currentColor"
                  class="bi bi-x-lg"
                  viewBox="0 0 16 16"
                >
                  <path d="M2.146 2.854a.5.5 0 1 1 .708-.708L8 7.293l5.146-5.147a.5.5 0 0 1 .708.708L8.707 8l5.147 5.146a.5.5 0 0 1-.708.708L8 8.707l-5.146 5.147a.5.5 0 0 1-.708-.708L7.293 8 2.146 2.854Z" />
                </svg>
              </div>
            ) : (
              <div
                className={styles.burger}
                onClick={() => setMenuActive(true)}
              >
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="40px"
                  height="40px"
                  fill="currentColor"
                  class="bi bi-list"
                  viewBox="0 0 16 16"
                >
                  <path
                    fill-rule="evenodd"
                    d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"
                  />
                </svg>
              </div>
            )}
            {menuActive && (
              <div className={styles.menu}>
                <Link
                  href="/"
                  className={styles.link}
                  onClick={() => setMenuActive(false)}
                >
                  <Image
                    src="/img/logo-blanco.png"
                    alt="phenomena"
                    className={styles.logo}
                    width={1612}
                    height={213}
                  />
                </Link>
                <Link
                  href="/music"
                  className={styles.link}
                  onClick={() => setMenuActive(false)}
                >
                  MUSIC MANAGEMENT:
                </Link>
                <Link
                  href="/branding"
                  className={styles.link}
                  onClick={() => setMenuActive(false)}
                >
                  RE BRANDING:
                </Link>
                <Link
                  href="/asesoria"
                  className={styles.link}
                  onClick={() => setMenuActive(false)}
                >
                  ASESORÍA CREATIVA:
                </Link>
                <Link
                  href="/social"
                  className={styles.link}
                  onClick={() => setMenuActive(false)}
                >
                  SOCIAL MEDIA:
                </Link>
                <Link
                  href="/stylist"
                  className={styles.link}
                  onClick={() => setMenuActive(false)}
                >
                  STYLIST:
                </Link>
                <Link
                  href="/produccion"
                  className={styles.link}
                  onClick={() => setMenuActive(false)}
                >
                  PRODUCCIÓN AUDIOVISUAL:
                </Link>
                <Link
                  href="/fotografia"
                  className={styles.link}
                  onClick={() => setMenuActive(false)}
                >
                  FOTOGRAFÍA:
                </Link>
                <div className={styles.contact}>
                  <Link
                    href="mailto:info@phenomena.com"
                    className={styles.link}
                    onClick={() => setMenuActive(false)}
                  >
                    info@phenomena.com
                  </Link>
                </div>
              </div>
            )}
          </nav>
          <div className={styles.homeContent}>
            <section className={styles.header}>
              <div className={styles.headerBox}>
                <Image
                  src="/img/logo-blanco.png"
                  alt="phenomena"
                  className={styles.nameImg}
                  width={1612}
                  height={213}
                />
              </div>
            </section>
          </div>
        </div>
      </main>
    </>
  );
}
