import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Image from "next/image";
import { useEffect, useState } from "react";
import Link from "next/link";

export default function Home() {
  const [menuActive, setMenuActive] = useState(false);

  return (
    <>
      <Head>
        <title>Phenomena</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.jpg" />
      </Head>
      <main>
        <nav className={`${styles.nav} ${menuActive && styles.navActive}`}>
          <div className={styles.burger} onClick={() => setMenuActive(true)}>
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="40px"
              height="40px"
              fill="currentColor"
              class="bi bi-list"
              viewBox="0 0 16 16"
            >
              <path
                fill-rule="evenodd"
                d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"
              />
            </svg>
          </div>
          {menuActive && (
            <div className={styles.menu}>
              <Link
                href="/music"
                className={styles.link}
                onClick={() => setMenuActive(false)}
              >
                MUSIC MANAGEMENT:
              </Link>
              <Link
                href="/branding"
                className={styles.link}
                onClick={() => setMenuActive(false)}
              >
                RE BRANDING:
              </Link>
              <Link
                href="/asesoria"
                className={styles.link}
                onClick={() => setMenuActive(false)}
              >
                ASESORÍA CREATIVA:
              </Link>
              <Link
                href="/social"
                className={styles.link}
                onClick={() => setMenuActive(false)}
              >
                SOCIAL MEDIA:
              </Link>
              <Link
                href="/stylist"
                className={styles.link}
                onClick={() => setMenuActive(false)}
              >
                STYLIST:
              </Link>
              <Link
                href="/produccion"
                className={styles.link}
                onClick={() => setMenuActive(false)}
              >
                PRODUCCIÓN AUDIOVISUAL:
              </Link>
              <Link
                href="/fotografia"
                className={styles.link}
                onClick={() => setMenuActive(false)}
              >
                FOTOGRAFÍA:
              </Link>
            </div>
          )}
        </nav>
        <div className={styles.homeContent}>
          <section className={styles.pageInfo}>
            <div className="container">
              <h2>MUSIC MANAGEMENT</h2>
              <div className={styles.divider} />
              <div className={styles.text}>
                <p>
                  Servicios de representación artística y relaciones públicas
                  que se enfocan en la exposición y posicionamiento de talento.
                </p>
                <p>
                  Creamos estrategias personalizadas para cada cliente,
                  identificamos oportunidades de negocio y construimos
                  relaciones sólidas con los medios, plataformas y líderes de
                  opinión relevantes en la industria.
                </p>
                <p>
                  &apos;eres libre de hacer lo que quieras nosotros te
                  guiamos... mientras sea cool, or we bullying u.jk0&apos;
                </p>
              </div>
              <h3>Talento:</h3>
              <div className={styles.artistas}>
                <h4>Juanpalitoschinos</h4>
                <p>lorem</p>
                <Image
                  src="/img/artista1.jpg"
                  width={1000}
                  height={400}
                  alt="artista"
                />
              </div>
            </div>
          </section>
        </div>
      </main>
    </>
  );
}
